// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/match.dart';
import 'models/match_round.dart';
import 'models/player.dart';
import 'models/player_match_points.dart';
import 'models/player_tournament_points.dart';
import 'models/tournament.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1572745648176918131),
    name: 'Match',
    lastPropertyId: const obx_int.IdUid(5, 5103843990581513960),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7750803975086610585),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1961568627713416482),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8230517020959680362),
        name: 'matchRoundId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6562123823263290604),
        relationTarget: 'MatchRound',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6952383737151679696),
        name: 'team1Score',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5103843990581513960),
        name: 'team2Score',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 6853198371567800634),
        name: 'team1',
        targetId: const obx_int.IdUid(3, 8296772384592528099),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 2745925058522224604),
        name: 'team2',
        targetId: const obx_int.IdUid(3, 8296772384592528099),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4285982042824457336),
    name: 'MatchRound',
    lastPropertyId: const obx_int.IdUid(4, 3088684982168167446),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7296436690690422169),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7093550582988408798),
        name: 'roundIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1120414197257234821),
        name: 'tournamentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3088684982168167446),
        name: 'id',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 2751569605124290884),
        name: 'players',
        targetId: const obx_int.IdUid(3, 8296772384592528099),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 2399894646209402714),
        name: 'playerMatchPoints',
        targetId: const obx_int.IdUid(5, 2624052262967590644),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'matches',
        srcEntity: 'Match',
        srcField: 'matchRound',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8296772384592528099),
    name: 'Player',
    lastPropertyId: const obx_int.IdUid(6, 4469192148008349224),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7716340757713379615),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6453986488739060193),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3486178520328339207),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9041997301162730289),
        name: 'points',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2744049701637512134),
        name: 'sex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4469192148008349224),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(7, 1816435644254693833),
        name: 'players',
        targetId: const obx_int.IdUid(3, 8296772384592528099),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 689409871988813927),
    name: 'Tournament',
    lastPropertyId: const obx_int.IdUid(4, 7959767323344071364),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2998323389914615224),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8935831150682355523),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2426599791600365274),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7959767323344071364),
        name: 'pointPerMatch',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 3541512027940101649),
        name: 'players',
        targetId: const obx_int.IdUid(3, 8296772384592528099),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(6, 3230888488136088208),
        name: 'playerTournamentPoints',
        targetId: const obx_int.IdUid(6, 1222990246352220030),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(8, 4581666233497107557),
        name: 'rounds',
        targetId: const obx_int.IdUid(2, 4285982042824457336),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2624052262967590644),
    name: 'PlayerMatchPoints',
    lastPropertyId: const obx_int.IdUid(4, 7372454683831204579),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4850481673888937309),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6728942110986964324),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3258306974513552263),
        name: 'points',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7372454683831204579),
        name: 'sittingOver',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 1222990246352220030),
    name: 'PlayerTournamentPoints',
    lastPropertyId: const obx_int.IdUid(3, 2215129217249584063),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5114372720486474084),
        name: 'oid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4201432929568633001),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2215129217249584063),
        name: 'points',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 1222990246352220030),
    lastIndexId: const obx_int.IdUid(2, 4575272826415533129),
    lastRelationId: const obx_int.IdUid(8, 4581666233497107557),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [4575272826415533129],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Match: obx_int.EntityDefinition<Match>(
      model: _entities[0],
      toOneRelations: (Match object) => [object.matchRound],
      toManyRelations: (Match object) => {
        obx_int.RelInfo<Match>.toMany(1, object.oid): object.team1,
        obx_int.RelInfo<Match>.toMany(2, object.oid): object.team2,
      },
      getId: (Match object) => object.oid,
      setId: (Match object, int id) {
        object.oid = id;
      },
      objectToFB: (Match object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        fbb.startTable(6);
        fbb.addInt64(0, object.oid);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.matchRound.targetId);
        fbb.addInt64(3, object.team1Score);
        fbb.addInt64(4, object.team2Score);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final team1ScoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final team2ScoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Match(
          oid: oidParam,
          id: idParam,
          team1Score: team1ScoreParam,
          team2Score: team2ScoreParam,
        );
        object.matchRound.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.matchRound.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Match>(
          object.team1,
          store,
          obx_int.RelInfo<Match>.toMany(1, object.oid),
        );
        obx_int.InternalToManyAccess.setRelInfo<Match>(
          object.team2,
          store,
          obx_int.RelInfo<Match>.toMany(2, object.oid),
        );
        return object;
      },
    ),
    MatchRound: obx_int.EntityDefinition<MatchRound>(
      model: _entities[1],
      toOneRelations: (MatchRound object) => [],
      toManyRelations: (MatchRound object) => {
        obx_int.RelInfo<MatchRound>.toMany(4, object.oid): object.players,
        obx_int.RelInfo<MatchRound>.toMany(5, object.oid):
            object.playerMatchPoints,
        obx_int.RelInfo<Match>.toOneBacklink(
          3,
          object.oid,
          (Match srcObject) => srcObject.matchRound,
        ): object.matches,
      },
      getId: (MatchRound object) => object.oid,
      setId: (MatchRound object, int id) {
        object.oid = id;
      },
      objectToFB: (MatchRound object, fb.Builder fbb) {
        final tournamentIdOffset = object.tournamentId == null
            ? null
            : fbb.writeString(object.tournamentId!);
        final idOffset = object.id == null ? null : fbb.writeString(object.id!);
        fbb.startTable(5);
        fbb.addInt64(0, object.oid);
        fbb.addInt64(1, object.roundIndex);
        fbb.addOffset(2, tournamentIdOffset);
        fbb.addOffset(3, idOffset);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final roundIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = MatchRound(oid: oidParam, roundIndex: roundIndexParam)
          ..tournamentId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10);
        obx_int.InternalToManyAccess.setRelInfo<MatchRound>(
          object.players,
          store,
          obx_int.RelInfo<MatchRound>.toMany(4, object.oid),
        );
        obx_int.InternalToManyAccess.setRelInfo<MatchRound>(
          object.playerMatchPoints,
          store,
          obx_int.RelInfo<MatchRound>.toMany(5, object.oid),
        );
        obx_int.InternalToManyAccess.setRelInfo<MatchRound>(
          object.matches,
          store,
          obx_int.RelInfo<Match>.toOneBacklink(
            3,
            object.oid,
            (Match srcObject) => srcObject.matchRound,
          ),
        );
        return object;
      },
    ),
    Player: obx_int.EntityDefinition<Player>(
      model: _entities[2],
      toOneRelations: (Player object) => [],
      toManyRelations: (Player object) => {
        obx_int.RelInfo<Player>.toMany(7, object.oid): object.players,
      },
      getId: (Player object) => object.oid,
      setId: (Player object, int id) {
        object.oid = id;
      },
      objectToFB: (Player object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final sexOffset = fbb.writeString(object.sex);
        fbb.startTable(7);
        fbb.addInt64(0, object.oid);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.points);
        fbb.addOffset(4, sexOffset);
        fbb.addBool(5, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final pointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final sexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = Player(
          oid: oidParam,
          id: idParam,
          name: nameParam,
          points: pointsParam,
          sex: sexParam,
          isDeleted: isDeletedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Player>(
          object.players,
          store,
          obx_int.RelInfo<Player>.toMany(7, object.oid),
        );
        return object;
      },
    ),
    Tournament: obx_int.EntityDefinition<Tournament>(
      model: _entities[3],
      toOneRelations: (Tournament object) => [],
      toManyRelations: (Tournament object) => {
        obx_int.RelInfo<Tournament>.toMany(3, object.oid): object.players,
        obx_int.RelInfo<Tournament>.toMany(6, object.oid):
            object.playerTournamentPoints,
        obx_int.RelInfo<Tournament>.toMany(8, object.oid): object.rounds,
      },
      getId: (Tournament object) => object.oid,
      setId: (Tournament object, int id) {
        object.oid = id;
      },
      objectToFB: (Tournament object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.oid);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.pointPerMatch);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final pointPerMatchParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Tournament(
          oid: oidParam,
          id: idParam,
          name: nameParam,
          pointPerMatch: pointPerMatchParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Tournament>(
          object.players,
          store,
          obx_int.RelInfo<Tournament>.toMany(3, object.oid),
        );
        obx_int.InternalToManyAccess.setRelInfo<Tournament>(
          object.playerTournamentPoints,
          store,
          obx_int.RelInfo<Tournament>.toMany(6, object.oid),
        );
        obx_int.InternalToManyAccess.setRelInfo<Tournament>(
          object.rounds,
          store,
          obx_int.RelInfo<Tournament>.toMany(8, object.oid),
        );
        return object;
      },
    ),
    PlayerMatchPoints: obx_int.EntityDefinition<PlayerMatchPoints>(
      model: _entities[4],
      toOneRelations: (PlayerMatchPoints object) => [],
      toManyRelations: (PlayerMatchPoints object) => {},
      getId: (PlayerMatchPoints object) => object.oid,
      setId: (PlayerMatchPoints object, int id) {
        object.oid = id;
      },
      objectToFB: (PlayerMatchPoints object, fb.Builder fbb) {
        final playerIdOffset = fbb.writeString(object.playerId);
        fbb.startTable(5);
        fbb.addInt64(0, object.oid);
        fbb.addOffset(1, playerIdOffset);
        fbb.addInt64(2, object.points);
        fbb.addBool(3, object.sittingOver);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final pointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sittingOverParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = PlayerMatchPoints(
          oid: oidParam,
          points: pointsParam,
          playerId: playerIdParam,
          sittingOver: sittingOverParam,
        );

        return object;
      },
    ),
    PlayerTournamentPoints: obx_int.EntityDefinition<PlayerTournamentPoints>(
      model: _entities[5],
      toOneRelations: (PlayerTournamentPoints object) => [],
      toManyRelations: (PlayerTournamentPoints object) => {},
      getId: (PlayerTournamentPoints object) => object.oid,
      setId: (PlayerTournamentPoints object, int id) {
        object.oid = id;
      },
      objectToFB: (PlayerTournamentPoints object, fb.Builder fbb) {
        final playerIdOffset = fbb.writeString(object.playerId);
        fbb.startTable(4);
        fbb.addInt64(0, object.oid);
        fbb.addOffset(1, playerIdOffset);
        fbb.addInt64(2, object.points);
        fbb.finish(fbb.endTable());
        return object.oid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final oidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final pointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PlayerTournamentPoints(
          oid: oidParam,
          points: pointsParam,
          playerId: playerIdParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Match] entity fields to define ObjectBox queries.
class Match_ {
  /// See [Match.oid].
  static final oid = obx.QueryIntegerProperty<Match>(
    _entities[0].properties[0],
  );

  /// See [Match.id].
  static final id = obx.QueryStringProperty<Match>(_entities[0].properties[1]);

  /// See [Match.matchRound].
  static final matchRound = obx.QueryRelationToOne<Match, MatchRound>(
    _entities[0].properties[2],
  );

  /// See [Match.team1Score].
  static final team1Score = obx.QueryIntegerProperty<Match>(
    _entities[0].properties[3],
  );

  /// See [Match.team2Score].
  static final team2Score = obx.QueryIntegerProperty<Match>(
    _entities[0].properties[4],
  );

  /// see [Match.team1]
  static final team1 = obx.QueryRelationToMany<Match, Player>(
    _entities[0].relations[0],
  );

  /// see [Match.team2]
  static final team2 = obx.QueryRelationToMany<Match, Player>(
    _entities[0].relations[1],
  );
}

/// [MatchRound] entity fields to define ObjectBox queries.
class MatchRound_ {
  /// See [MatchRound.oid].
  static final oid = obx.QueryIntegerProperty<MatchRound>(
    _entities[1].properties[0],
  );

  /// See [MatchRound.roundIndex].
  static final roundIndex = obx.QueryIntegerProperty<MatchRound>(
    _entities[1].properties[1],
  );

  /// See [MatchRound.tournamentId].
  static final tournamentId = obx.QueryStringProperty<MatchRound>(
    _entities[1].properties[2],
  );

  /// See [MatchRound.id].
  static final id = obx.QueryStringProperty<MatchRound>(
    _entities[1].properties[3],
  );

  /// see [MatchRound.players]
  static final players = obx.QueryRelationToMany<MatchRound, Player>(
    _entities[1].relations[0],
  );

  /// see [MatchRound.playerMatchPoints]
  static final playerMatchPoints =
      obx.QueryRelationToMany<MatchRound, PlayerMatchPoints>(
        _entities[1].relations[1],
      );

  /// see [MatchRound.matches]
  static final matches = obx.QueryBacklinkToMany<Match, MatchRound>(
    Match_.matchRound,
  );
}

/// [Player] entity fields to define ObjectBox queries.
class Player_ {
  /// See [Player.oid].
  static final oid = obx.QueryIntegerProperty<Player>(
    _entities[2].properties[0],
  );

  /// See [Player.id].
  static final id = obx.QueryStringProperty<Player>(_entities[2].properties[1]);

  /// See [Player.name].
  static final name = obx.QueryStringProperty<Player>(
    _entities[2].properties[2],
  );

  /// See [Player.points].
  static final points = obx.QueryIntegerProperty<Player>(
    _entities[2].properties[3],
  );

  /// See [Player.sex].
  static final sex = obx.QueryStringProperty<Player>(
    _entities[2].properties[4],
  );

  /// See [Player.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Player>(
    _entities[2].properties[5],
  );

  /// see [Player.players]
  static final players = obx.QueryRelationToMany<Player, Player>(
    _entities[2].relations[0],
  );
}

/// [Tournament] entity fields to define ObjectBox queries.
class Tournament_ {
  /// See [Tournament.oid].
  static final oid = obx.QueryIntegerProperty<Tournament>(
    _entities[3].properties[0],
  );

  /// See [Tournament.id].
  static final id = obx.QueryStringProperty<Tournament>(
    _entities[3].properties[1],
  );

  /// See [Tournament.name].
  static final name = obx.QueryStringProperty<Tournament>(
    _entities[3].properties[2],
  );

  /// See [Tournament.pointPerMatch].
  static final pointPerMatch = obx.QueryIntegerProperty<Tournament>(
    _entities[3].properties[3],
  );

  /// see [Tournament.players]
  static final players = obx.QueryRelationToMany<Tournament, Player>(
    _entities[3].relations[0],
  );

  /// see [Tournament.playerTournamentPoints]
  static final playerTournamentPoints =
      obx.QueryRelationToMany<Tournament, PlayerTournamentPoints>(
        _entities[3].relations[1],
      );

  /// see [Tournament.rounds]
  static final rounds = obx.QueryRelationToMany<Tournament, MatchRound>(
    _entities[3].relations[2],
  );
}

/// [PlayerMatchPoints] entity fields to define ObjectBox queries.
class PlayerMatchPoints_ {
  /// See [PlayerMatchPoints.oid].
  static final oid = obx.QueryIntegerProperty<PlayerMatchPoints>(
    _entities[4].properties[0],
  );

  /// See [PlayerMatchPoints.playerId].
  static final playerId = obx.QueryStringProperty<PlayerMatchPoints>(
    _entities[4].properties[1],
  );

  /// See [PlayerMatchPoints.points].
  static final points = obx.QueryIntegerProperty<PlayerMatchPoints>(
    _entities[4].properties[2],
  );

  /// See [PlayerMatchPoints.sittingOver].
  static final sittingOver = obx.QueryBooleanProperty<PlayerMatchPoints>(
    _entities[4].properties[3],
  );
}

/// [PlayerTournamentPoints] entity fields to define ObjectBox queries.
class PlayerTournamentPoints_ {
  /// See [PlayerTournamentPoints.oid].
  static final oid = obx.QueryIntegerProperty<PlayerTournamentPoints>(
    _entities[5].properties[0],
  );

  /// See [PlayerTournamentPoints.playerId].
  static final playerId = obx.QueryStringProperty<PlayerTournamentPoints>(
    _entities[5].properties[1],
  );

  /// See [PlayerTournamentPoints.points].
  static final points = obx.QueryIntegerProperty<PlayerTournamentPoints>(
    _entities[5].properties[2],
  );
}
